#!/usr/bin/env python3
"""cage_engine.py -- ticket cs-21: cage-spec comparison and the computed bump.

The core classification engine gate.py's `run_gate` calls once a repository
state carries a real old subject tree, a real new subject tree, and a
generated corpus (ticket 19). Two tracks combine into one whole-body bump,
exactly the way `CONTEXT.md`'s "a policy version covers the whole body"
already combines named-policy verdicts in rederive_bumps.py (reused here,
never re-derived, per spec.md's "Pairing and structural rules": "Major and
patch come from verdict movement. Minor comes from presence plus
`validationActions`."):

  Track 1 -- ValidatingPolicy admission. `rederive_bumps.classify_policy`,
  UNCHANGED, called per paired policy file. major = an existing policy's
  admission verdict narrows (admitted -> refused) for some corpus pod, or a
  brand-new Deny policy is added; minor = a brand-new Audit-only policy is
  added (it cannot refuse anything -- ticket 02's own resolution); patch =
  the passing set only ever widens. Reads per-policy outcomes, never a
  pooled CLI exit code -- `rederive_bumps.cel_pass` already calls
  `kyverno apply` one policy file at a time (ticket 01's own finding, reused
  directly rather than re-derived).

  Track 2 -- the cage/enforcement dial spec (spec.md, "What the gate
  measures": "Every workload is always caged, and the cage spec is what
  changes... the engine compares cage specs, not verdict enums"). cage-tier
  (graded/policies/cage-tier.yaml, a MutatingPolicy) has no
  `validationActions` and no pass/fail of its own -- `kyverno apply` always
  mutates, never fails -- so Track 1's admitted/refused vocabulary does not
  apply to it. For each corpus pod that claims a policy version, this
  computes the dial VALUES the pod would receive under the old body and the
  new body (a pure map lookup on the pod's `posture.acme.io/tier` label,
  defaulted to 'baseline' exactly as cage-tier.yaml's own CEL does -- see
  `effective_tier`) and classifies major when the new spec is not AT LEAST
  AS PERMISSIVE as the old one, at the SPEC level: a permissiveness partial
  order across the same fields graded/cage.py's TIERS table names (cpu, mem,
  priorityClass, dropAll, readOnlyRootFs, waf) -- never an enumerated list
  of surfaces. A tier policy that appends a sidecar, sets a priority class,
  flips two securityContext fields and drops capabilities all in one release
  still classifies from ONE spec-level comparison, not four separate dial
  checks that rot on the next mutation added.

  "There is no uncaged state" (spec.md) is modelled as the TOP of the
  permissiveness lattice: a pod cage-tier does not reach at all (the file
  absent on one side, or the pod does not claim a version) receives the
  fully-permissive degenerate spec, UNCAGED. "cage-tier newly added" then
  falls out of the SAME per-pod comparison as any other tightening (uncaged
  -> a real tier is a narrowing, hence major) with no special case, and
  "cage-tier removed" falls out as a widening (patch), also with no special
  case -- neither needs its own branch.

Movement entries name the corpus entries that moved (the pod filenames) and
the CEL expression responsible: the sole `validations[]` expression for a
Track 1 policy (every corpus policy body carries exactly one), or the
`dial` variable's own CEL expression for Track 2 (the one expression that
encodes every tier's dial values -- spec-level, not per-dial).

A policy `kind` this engine does not model (GeneratingPolicy, a plain
PriorityClass, a MutatingPolicy with no `dial` variable such as
posture/policies/stamp-posture.yaml) is skipped, not guessed at -- ponytail:
the two tracks above are what this ticket names; a third surface is a future
ticket's job.

ponytail: a genuine, disclosed gap, not silently glossed over -- a corpus
generated by corpus_generator.main()'s LIVE default path (both subjects
materialized from real released version trees, one shared `inside_pin` baked
into every pod, exactly as its own docstring says: "one declared 'inside'
pin ... is a property of the version under test, not of old vs new") pins
every pod to the NEW version only. A self-scoped mandatory-member policy
(render-version-tree.py's `only-this-policy-version` matchCondition) on the
OLD side then matches none of those pods at all, so it reads as trivially
admitted for every one of them -- and if the NEW side's copy denies some of
those same pods on unrelated grounds, this shows up as a spurious major that
has nothing to do with the OLD and NEW policy BODIES actually differing. The
three known-good historical bumps this ticket must rederive predate
self-scoping entirely (they use the old `objectSelector` placeholder scheme,
not render-version-tree.py's matchConditions self-scope) and so never hit
this, and it is exactly the "pair on identity, not on a version-pinned
label" concern spec.md's "Pairing and structural rules" hands to a later
ticket -- relabelling each pod's claim per side before evaluating a
self-scoped policy is that ticket's repair, not invented here.

Usage:
    cage_engine.py --selfcheck
"""
from __future__ import annotations

import ast
import math
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

import rederive_bumps

HERE = Path(__file__).resolve().parent
REPO = HERE.parent

PIN_LABEL = "policy-as-versioned.dev/policy-version"
TIER_LABEL = "posture.acme.io/tier"
TIER_ORDER = ["baseline", "restricted", "quarantine"]  # loosest -> tightest

# rederive_bumps.RANK has no entry for "removed" (no PAIRS case ever drops a
# policy) -- removing a validating gate can only ever admit MORE than before
# (it can never newly refuse anything), so for AGGREGATION purposes it ranks
# no higher than "patch". The raw "removed" verdict string is still kept on
# the Movement record itself, for a reviewer.
RANK = {**rederive_bumps.RANK, "removed": rederive_bumps.RANK["patch"]}


# ---------------------------------------------------------------------------
# Track 2: the cage-spec permissiveness lattice
# ---------------------------------------------------------------------------

WAF_RANK = {"none": 2, "light": 1, "heavy": 0}  # higher = more permissive


def _pc_value_table() -> dict[str, int]:
    """{PriorityClass name: its real `value:` field}, read once from the
    actual committed graded/policies/priorityclasses.yaml -- real Kubernetes
    scheduling-priority numbers, never invented placeholders. That file's own
    docstring: a HIGHER value schedules with more preference, i.e. the
    workload is LESS caged / more privileged -- so a higher value is more
    permissive, the same sense every other field in CageSpec ranks on."""
    docs = yaml.safe_load_all((REPO / "graded" / "policies" / "priorityclasses.yaml").read_text())
    return {d["metadata"]["name"]: d["value"] for d in docs if d and d.get("kind") == "PriorityClass"}


PC_VALUES = _pc_value_table()


def _pc_value(pc_name: str | None) -> int:
    """Real scheduling-priority value for `pc_name`. None (UNCAGED -- no
    PriorityClass applies to the pod at all) sits at the cluster's own
    default of 0, ahead of every real caged tier (priorityclasses.yaml's own
    docstring: "healthy in-currency workloads (default globalDefault priority
    0) outrank every caged tier"). A versioned name render-version-tree.py
    stamps as '<base>-<slug>' (_versioned_name rewrites the name/label only
    -- never the `value:` field) matches on its base-name prefix, so a
    real rendered version tree resolves to the same real number as the
    unversioned authoring copy."""
    if pc_name is None:
        return 0
    if pc_name in PC_VALUES:
        return PC_VALUES[pc_name]
    for base, value in PC_VALUES.items():
        if pc_name.startswith(base + "-"):
            return value
    raise KeyError(
        f"unknown PriorityClass {pc_name!r}: not in graded/policies/priorityclasses.yaml "
        f"and not a versioned form of one of {sorted(PC_VALUES)}"
    )


@dataclass(frozen=True)
class CageSpec:
    cpu: float  # millicores; math.inf = uncaged
    mem: float  # bytes; math.inf = uncaged
    pc: str | None  # the ACTUAL PriorityClass name this tier assigns; None = uncaged
    drop_all: bool
    read_only_root_fs: bool
    waf: str  # 'none'|'light'|'heavy'


UNCAGED = CageSpec(cpu=math.inf, mem=math.inf, pc=None,
                    drop_all=False, read_only_root_fs=False, waf="none")


def _millicores(v: str) -> float:
    return float(v[:-1]) if v.endswith("m") else float(v) * 1000


def _mem_bytes(v: str) -> float:
    units = {"Ki": 1024, "Mi": 1024**2, "Gi": 1024**3, "Ti": 1024**4}
    for suf, mult in units.items():
        if v.endswith(suf):
            return float(v[: -len(suf)]) * mult
    return float(v)


def dial_table(cage_tier_body: dict) -> tuple[dict[str, CageSpec], str]:
    """Parses the `dial` variable's CEL map literal into {tier: CageSpec},
    plus the raw expression text (for movement reporting). Deterministic, no
    subprocess needed for a pure lookup table -- graded/cage.py's own
    docstring: "the tier -> dials expansion is a pure CEL map lookup:
    deterministic, no surprises." The map syntax is CEL, not YAML, but its
    single-quoted string literals and braces are valid Python literal syntax
    once the trailing `[variables.tier]` index is stripped, so
    `ast.literal_eval` reads it directly -- no separate CEL parser needed."""
    variables = cage_tier_body["spec"]["variables"]
    dial_var = next(v for v in variables if v["name"] == "dial")
    expr = dial_var["expression"]
    literal = expr.rsplit("[variables.tier]", 1)[0].strip()
    raw = ast.literal_eval(literal)
    out: dict[str, CageSpec] = {}
    for tier, dial in raw.items():
        harden = dial["harden"] == "true"
        waf = "none" if dial["wafCpu"] == "0" else (
            "light" if _millicores(dial["wafCpu"]) <= 100 else "heavy"
        )
        out[tier] = CageSpec(
            cpu=_millicores(dial["cpu"]), mem=_mem_bytes(dial["mem"]),
            pc=dial["pc"], drop_all=harden, read_only_root_fs=harden, waf=waf,
        )
    return out, expr


def has_dial_variable(body: dict) -> bool:
    return any(v.get("name") == "dial" for v in (body.get("spec", {}).get("variables") or []))


def permissive_rank(spec: CageSpec) -> dict[str, float]:
    """Higher, per field, is more permissive. Returned as a dict (not a
    single collapsed score) so a caller can name WHICH fields regressed for
    a reviewer -- the VERDICT is still one spec-level comparison (see
    `at_least_as_permissive`), never four separate dial checks.

    priorityClass ranks on the ACTUAL assigned PriorityClass's real
    scheduling-priority `value:` (`_pc_value`, read from the real committed
    priorityclasses.yaml) -- never a rank re-derived from the pod's own tier
    label. The tier label is the same on both sides of any comparison by
    construction (`classify_cage_tier` looks up `old_table[tier]` and
    `new_table[tier]` with the identical `tier` key), so a rank keyed off it
    can never move even when the tier's `pc` field is repointed at a
    genuinely different, more-or-less-privileged PriorityClass."""
    return {
        "cpu": spec.cpu,
        "mem": spec.mem,
        "priorityClass": _pc_value(spec.pc),
        "dropAll": 0 if spec.drop_all else 1,
        "readOnlyRootFs": 0 if spec.read_only_root_fs else 1,
        "waf": WAF_RANK[spec.waf],
    }


def at_least_as_permissive(old: CageSpec, new: CageSpec) -> tuple[bool, list[str], list[str]]:
    """(ok, regressed fields, widened fields). `ok` is False the moment ANY
    field of `new` is less permissive than `old` -- a genuine partial order,
    not a score: one field improving never excuses another regressing."""
    old_r, new_r = permissive_rank(old), permissive_rank(new)
    regressed = [f for f in old_r if new_r[f] < old_r[f]]
    widened = [f for f in old_r if new_r[f] > old_r[f]]
    return not regressed, regressed, widened


def claims_version(pod: dict) -> bool:
    return bool((pod.get("metadata") or {}).get("labels", {}).get(PIN_LABEL, ""))


def effective_tier(pod: dict) -> str:
    """Mirrors cage-tier.yaml's own CEL: an absent or unrecognized tier
    label defaults to 'baseline', the loosest tier -- never a no-op skip."""
    raw = (pod.get("metadata") or {}).get("labels", {}).get(TIER_LABEL, "baseline")
    return raw if raw in TIER_ORDER else "baseline"


# ---------------------------------------------------------------------------
# Movement -- the shared shape both tracks report through
# ---------------------------------------------------------------------------

@dataclass
class Movement:
    policy: str
    verdict: str  # "major" | "minor" | "patch" | "none" | "removed"
    entries: list[str] = field(default_factory=list)
    expressions: list[str] = field(default_factory=list)
    detail: str = ""

    def as_dict(self) -> dict:
        return {
            "policy": self.policy,
            "verdict": self.verdict,
            "entries": list(self.entries),
            "expressions": list(self.expressions),
            "detail": self.detail,
        }


_MOVED_ENTRY = re.compile(
    r"^(?P<entry>\S+): (?:admitted -> REFUSED|refused -> admitted)"
)


def _entries_from_detail(detail: str) -> list[str]:
    """rederive_bumps.classify_policy's own `detail` string is
    "<fixture-stem>: admitted -> REFUSED" segments joined by '; ' -- this
    pulls the fixture stems back out rather than re-deriving the movement."""
    out = []
    for part in detail.split("; "):
        m = _MOVED_ENTRY.match(part.strip())
        if m:
            out.append(m.group("entry"))
    return out


def _validation_expressions(policy_file: Path) -> list[str]:
    doc = yaml.safe_load(policy_file.read_text())
    return [v["expression"] for v in (doc.get("spec", {}).get("validations") or [])]


# ---------------------------------------------------------------------------
# Track 1
# ---------------------------------------------------------------------------

def classify_validating(name: str, old_file: Path | None, new_file: Path | None,
                         pods: list[Path]) -> Movement:
    c = rederive_bumps.classify_policy(old_file, new_file, pods)
    exprs = _validation_expressions(new_file or old_file) if (new_file or old_file) else []
    return Movement(policy=name, verdict=c.verdict,
                     entries=_entries_from_detail(c.detail),
                     expressions=exprs, detail=c.detail)


# ---------------------------------------------------------------------------
# Track 2
# ---------------------------------------------------------------------------

def classify_cage_tier(name: str, old_file: Path | None, new_file: Path | None,
                        pods: list[Path]) -> Movement:
    old_table, old_expr = dial_table(yaml.safe_load(old_file.read_text())) if old_file else ({}, None)
    new_table, new_expr = dial_table(yaml.safe_load(new_file.read_text())) if new_file else ({}, None)

    regressed_entries: list[str] = []
    widened_entries: list[str] = []
    detail_parts: list[str] = []
    for pod_file in pods:
        pod = yaml.safe_load(pod_file.read_text())
        if not claims_version(pod):
            continue  # not matched by cage-tier at all, either side -- no spec to compare
        tier = effective_tier(pod)
        old_spec = old_table.get(tier, UNCAGED)
        new_spec = new_table.get(tier, UNCAGED)
        ok, regressed, widened = at_least_as_permissive(old_spec, new_spec)
        if not ok:
            regressed_entries.append(pod_file.stem)
            detail_parts.append(f"{pod_file.stem} (tier={tier}): {', '.join(regressed)} narrowed")
        elif widened:
            widened_entries.append(pod_file.stem)

    expr = new_expr or old_expr
    if regressed_entries:
        verdict = "major"
        detail = "; ".join(detail_parts)
        entries = regressed_entries
    elif widened_entries:
        verdict = "patch"
        detail = f"{len(widened_entries)} corpus entr{'y' if len(widened_entries) == 1 else 'ies'} widened"
        entries = widened_entries
    else:
        verdict = "none"
        detail = "no corpus entry's cage spec moved"
        entries = []

    return Movement(policy=name, verdict=verdict, entries=entries,
                     expressions=[expr] if expr else [], detail=detail)


# ---------------------------------------------------------------------------
# Dispatch and whole-repo aggregation
# ---------------------------------------------------------------------------

def classify_pair(name: str, old_file: Path | None, new_file: Path | None,
                   pods: list[Path]) -> Movement | None:
    sample = old_file or new_file
    # A multi-document file (e.g. priorityclasses.yaml, three PriorityClass
    # docs in one file) is never a policy this engine models -- peek at the
    # first document's `kind` only, rather than choking on the stream shape.
    body = next(yaml.safe_load_all(sample.read_text()), {}) or {}
    kind = body.get("kind")
    if kind == "ValidatingPolicy":
        return classify_validating(name, old_file, new_file, pods)
    if kind == "MutatingPolicy" and has_dial_variable(body):
        return classify_cage_tier(name, old_file, new_file, pods)
    return None  # not modeled by this engine -- see module docstring


def pair_by_filename(old_dir: Path, new_dir: Path) -> dict[str, tuple[Path | None, Path | None]]:
    names = {f.name for f in old_dir.glob("*.yaml")} | {f.name for f in new_dir.glob("*.yaml")}
    out = {}
    for n in sorted(names):
        old_f = old_dir / n if (old_dir / n).exists() else None
        new_f = new_dir / n if (new_dir / n).exists() else None
        out[n] = (old_f, new_f)
    return out


@dataclass
class ClassificationResult:
    computed_bump: str
    movement: list[Movement]


def classify_repo(old_dir: Path, new_dir: Path, pods: list[Path]) -> ClassificationResult:
    """The whole-body computed bump: pair policy files by filename (the
    canonical, unversioned names render-version-tree.py and
    corpus_generator._materialize_subject already write), classify each
    pair, and take the most significant verdict -- exactly
    rederive_bumps.whole_body_bump's own combining rule, reused for the same
    reason it was reused there: CONTEXT.md scopes semver at the whole-body
    level."""
    pairs = pair_by_filename(old_dir, new_dir)
    movement = [m for m in (classify_pair(n, o, w, pods) for n, (o, w) in pairs.items()) if m is not None]
    top_rank = max((RANK[m.verdict] for m in movement), default=0)
    # Pick the bump CLASS name at the top rank. "removed" has no separate
    # verdict class of its own (spec.md doesn't name one) -- it aggregates
    # at patch's rank, so a removal that's the single highest-ranked
    # movement must still be *reported* as "patch", not dropped from the
    # candidate set entirely.
    at_top = {("patch" if m.verdict == "removed" else m.verdict)
              for m in movement if RANK[m.verdict] == top_rank}
    computed_bump = next((v for v in ("major", "minor", "patch") if v in at_top), "none")
    return ClassificationResult(computed_bump=computed_bump, movement=movement)


# ---------------------------------------------------------------------------
# selfcheck
# ---------------------------------------------------------------------------

_CAGE_TIER_TMPL = """\
apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: cage-tier
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchConditions:
    - name: claims-a-policy-version
      expression: >-
        object.metadata.?labels['policy-as-versioned.dev/policy-version'].orValue('') != ''
  variables:
    - name: dial
      expression: >-
        {DIAL}[variables.tier]
"""


def _dial_literal(baseline_cpu="500m", baseline_mem="256Mi", baseline_waf="0",
                   baseline_pc="cage-baseline"):
    return (
        "{'baseline':{'cpu':'%s','mem':'%s','pc':'%s','harden':'false',"
        "'wafCpu':'%s','wafMem':'0'},"
        "'restricted':{'cpu':'250m','mem':'128Mi','pc':'cage-restricted','harden':'true',"
        "'wafCpu':'100m','wafMem':'128Mi'},"
        "'quarantine':{'cpu':'100m','mem':'64Mi','pc':'cage-quarantine','harden':'true',"
        "'wafCpu':'250m','wafMem':'256Mi'}}"
        % (baseline_cpu, baseline_mem, baseline_pc, baseline_waf)
    )


def _write_cage_tier(path: Path, **dial_kwargs) -> None:
    path.write_text(_CAGE_TIER_TMPL.format(DIAL=_dial_literal(**dial_kwargs)))


def _write_pod(path: Path, name: str, tier: str | None, claims: bool = True) -> None:
    labels = {}
    if claims:
        labels[PIN_LABEL] = "1.0.0"
    if tier is not None:
        labels[TIER_LABEL] = tier
    yaml_doc = {
        "apiVersion": "v1", "kind": "Pod",
        "metadata": {"name": name, "labels": labels},
        "spec": {"containers": [{"name": "app", "image": "nginx:1.25"}]},
    }
    path.write_text(yaml.safe_dump(yaml_doc))


def selfcheck() -> None:
    import tempfile

    # 1. dial_table parses the REAL cage-tier.yaml body without error, and
    #    the three tiers it names match graded/cage.py's own TIERS keys --
    #    a smoke test against the real, not just a synthetic, file.
    repo = Path(__file__).resolve().parent.parent
    real_body = yaml.safe_load((repo / "graded" / "policies" / "cage-tier.yaml").read_text())
    real_table, real_expr = dial_table(real_body)
    assert set(real_table) == {"baseline", "restricted", "quarantine"}, real_table
    assert real_table["baseline"].cpu == 500 and real_table["quarantine"].cpu == 100, real_table
    assert real_table["baseline"].drop_all is False and real_table["quarantine"].drop_all is True
    assert "variables.tier" in real_expr

    # 2. the permissiveness lattice: UNCAGED is at least as permissive as
    #    every real tier, and no real tier is at least as permissive as
    #    UNCAGED (going from unrestricted to any real cage always narrows).
    for t in ("baseline", "restricted", "quarantine"):
        ok, regressed, _ = at_least_as_permissive(UNCAGED, real_table[t])
        assert not ok and regressed, (t, regressed)
        ok2, _, _ = at_least_as_permissive(real_table[t], UNCAGED)
        assert ok2

    # 3. tighter tiers are strictly less permissive than looser ones, on
    #    every field the ticket names.
    b, r, q = real_table["baseline"], real_table["restricted"], real_table["quarantine"]
    for tighter, looser in ((r, b), (q, r), (q, b)):
        ok, regressed, _ = at_least_as_permissive(looser, tighter)
        assert not ok and regressed, (looser, tighter, regressed)

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)

        # 4. Track 2, a genuine tightening: baseline's cpu limit drops
        #    500m -> 250m between old and new. A pod at the (defaulted)
        #    baseline tier must classify major, name itself as a moved
        #    corpus entry, and name the `dial` CEL expression -- never an
        #    enumerated "cpu changed" surface list.
        old_dir, new_dir = td / "old", td / "new"
        old_dir.mkdir(); new_dir.mkdir()
        _write_cage_tier(old_dir / "cage-tier.yaml", baseline_cpu="500m")
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_cpu="250m")
        pods_dir = td / "pods"
        pods_dir.mkdir()
        _write_pod(pods_dir / "claiming-default-tier.yaml", "p1", tier=None)
        _write_pod(pods_dir / "claiming-restricted.yaml", "p2", tier="restricted")
        _write_pod(pods_dir / "not-claiming.yaml", "p3", tier="baseline", claims=False)
        pods = sorted(pods_dir.glob("*.yaml"))

        m = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", new_dir / "cage-tier.yaml", pods)
        assert m.verdict == "major", m
        assert "claiming-default-tier" in m.entries, m.entries  # absent tier label defaults to baseline
        assert "claiming-restricted" not in m.entries, m.entries  # restricted's dials untouched
        assert "not-claiming" not in m.entries, m.entries  # never matched by cage-tier at all
        assert m.expressions == [_dial_literal(baseline_cpu="250m") + "[variables.tier]"], m.expressions

        # 5. a widen-only change (baseline's mem raised) classifies patch,
        #    never major, and names the widened entry.
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_cpu="500m", baseline_mem="512Mi")
        m2 = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", new_dir / "cage-tier.yaml", pods)
        assert m2.verdict == "patch", m2
        assert "claiming-default-tier" in m2.entries, m2.entries

        # 6. no change at all classifies none.
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_cpu="500m")
        m3 = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", new_dir / "cage-tier.yaml", pods)
        assert m3.verdict == "none" and m3.entries == [], m3

        # 7. spec-level, not dial-level: ONE field regresses (cpu tightens)
        #    while ANOTHER improves in the SAME release (waf drops from
        #    'light' to 'none' on baseline) -- still major. A partial order
        #    never lets one field's improvement excuse another's regression.
        _write_cage_tier(old_dir / "cage-tier.yaml", baseline_cpu="500m", baseline_waf="100m")
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_cpu="250m", baseline_waf="0")
        m4 = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", new_dir / "cage-tier.yaml", pods)
        assert m4.verdict == "major", m4
        assert "cpu" in m4.detail, m4.detail  # named the field that actually regressed
        _write_cage_tier(old_dir / "cage-tier.yaml", baseline_cpu="500m")  # restore for the rest

        # 8. cs-21 regression guard: priorityClass permissiveness must come
        #    from the ACTUAL assigned PriorityClass value, not from a rank
        #    re-derived off the pod's own tier label. Every OTHER field is
        #    held identical; only baseline's `pc` is repointed from
        #    'cage-baseline' (real value -10) to 'cage-quarantine' (real
        #    value -1000, see graded/policies/priorityclasses.yaml) -- a
        #    real narrowing (workload evicted far sooner under pressure). The
        #    old (pre-fix) code derived priorityClass purely from
        #    TIER_ORDER.index(tier_name), and BOTH sides look up the SAME
        #    tier key ('baseline') for this pod -- so tier_name was identical
        #    on both sides BY CONSTRUCTION and this real change was
        #    completely invisible (verdict came back "none"). Proven by
        #    breaking the fix (reverting permissive_rank to key off tier_name
        #    again) and confirming this assertion fails before restoring it.
        _write_cage_tier(old_dir / "cage-tier.yaml", baseline_pc="cage-baseline")
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_pc="cage-quarantine")
        m_pc = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", new_dir / "cage-tier.yaml", pods)
        assert m_pc.verdict == "major", m_pc
        assert "claiming-default-tier" in m_pc.entries, m_pc.entries
        assert "priorityClass" in m_pc.detail, m_pc.detail  # named the field that actually regressed
        _write_cage_tier(old_dir / "cage-tier.yaml", baseline_pc="cage-baseline")  # restore for the rest
        _write_cage_tier(new_dir / "cage-tier.yaml", baseline_cpu="500m")  # restore for the rest

        # 9. cage-tier newly added (absent on old side entirely): every
        #    claiming pod narrows from the uncaged top of the lattice -- no
        #    special case, it falls out of the same per-pod comparison.
        m5 = classify_cage_tier("cage-tier", None, new_dir / "cage-tier.yaml", pods)
        assert m5.verdict == "major", m5
        assert set(m5.entries) == {"claiming-default-tier", "claiming-restricted"}, m5.entries

        # 10. cage-tier removed entirely: every claiming pod widens to
        #    uncaged -- patch, again no special case.
        m6 = classify_cage_tier("cage-tier", old_dir / "cage-tier.yaml", None, pods)
        assert m6.verdict == "patch", m6

        # 11. "the gate never estimates viability... it prints one sentence
        #     instead" -- the major-narrowing detail is one sentence (no
        #     newline, no bullet points) and carries no viability language.
        assert "\n" not in m.detail, m.detail
        for word in ("viable", "viability", "%", "estimate", "workloads would"):
            assert word not in m.detail.lower(), (word, m.detail)

    # 12. Track 1: unchanged, direct reuse of rederive_bumps.classify_policy
    #     (not re-derived) -- proves the refactor point of this ticket
    #     without duplicating ticket 01's own logic.
    fx = rederive_bumps.ALL_FIXTURES
    dept_old = rederive_bumps.CORPUS / "department-label-1.0.0.yaml"
    dept_new = rederive_bumps.CORPUS / "department-label-2.0.0.yaml"
    mv = classify_validating("require-department-label", dept_old, dept_new, fx)
    assert mv.verdict == "major", mv
    assert mv.entries, "a major admission narrowing must name the fixtures that moved"
    assert mv.expressions == _validation_expressions(dept_new), mv.expressions

    # 13. classify_repo: the three known-good bumps, reproduced through THIS
    #     module's own directory-pairing + whole-body aggregation, not just
    #     the single-policy primitive above.
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        old1, new1 = td / "1.0.0", td / "2.0.0"
        old1.mkdir(); new1.mkdir()
        (old1 / "require-department-label.yaml").write_text(dept_old.read_text())
        (new1 / "require-department-label.yaml").write_text(dept_new.read_text())
        r1 = classify_repo(old1, new1, fx)
        assert r1.computed_bump == "major", r1.computed_bump

        old2, new2 = td / "2.0.1", td / "2.1.1"
        old2.mkdir(); new2.mkdir()
        (old2 / "require-department-label.yaml").write_text(
            (rederive_bumps.CORPUS / "department-label-2.0.0.yaml").read_text())
        (new2 / "require-department-label.yaml").write_text(
            (rederive_bumps.CORPUS / "department-label-2.0.0.yaml").read_text())
        (old2 / "require-known-department-label.yaml").write_text(
            (rederive_bumps.CORPUS / "known-department-label-2.0.1.yaml").read_text())
        (new2 / "require-known-department-label.yaml").write_text(
            (rederive_bumps.CORPUS / "known-department-label-2.1.1.yaml").read_text())
        (new2 / "require-owner-annotation.yaml").write_text(
            (rederive_bumps.CORPUS / "owner-annotation-2.1.1.yaml").read_text())
        r2 = classify_repo(old2, new2, fx)
        assert r2.computed_bump == "minor", r2.computed_bump  # whole-body: minor dominates the patch widening
        verdicts = {m.policy: m.verdict for m in r2.movement}
        assert verdicts == {
            "require-department-label.yaml": "none",
            "require-known-department-label.yaml": "patch",
            "require-owner-annotation.yaml": "minor",
        }, verdicts

        # 14. classify_repo when the single highest-ranked movement in the
        #     release is a Track-1 policy REMOVAL: "removed" has no bump
        #     class of its own, but it ranks at patch's rank, so it must
        #     still surface as computed_bump == "patch" -- not fall out of
        #     the candidate set and report "none" (cs-21 regression guard).
        old3, new3 = td / "removal-old", td / "removal-new"
        old3.mkdir(); new3.mkdir()
        (old3 / "require-department-label.yaml").write_text(dept_new.read_text())
        r3 = classify_repo(old3, new3, fx)
        assert r3.computed_bump == "patch", r3.computed_bump
        assert [m.verdict for m in r3.movement] == ["removed"], r3.movement

    print(
        "selfcheck ok: dial_table parses the real cage-tier.yaml; UNCAGED sits at "
        "the top of the permissiveness lattice, every real tier below it, tighter "
        "tiers below looser ones; a dial tightening classifies major and names the "
        "moved corpus entries and the dial CEL expression (never an enumerated dial "
        "list); a widen-only change is patch; no change is none; one field "
        "regressing while another improves is still major (spec-level, not "
        "dial-level); priorityClass ranks on the ACTUAL assigned PriorityClass's "
        "real value, so a tier's pc field repointed at a different PriorityClass "
        "registers as major even with every other dial untouched (cs-21 regression "
        "guard); cage-tier added/removed fall out of the same per-pod "
        "comparison with no special case; the major detail is one sentence with no "
        "viability language; Track 1 reuses rederive_bumps.classify_policy "
        "unchanged; classify_repo reproduces the three known-good bumps; a "
        "whole-body release whose only movement is a policy removal computes patch"
    )


def main(argv: list[str]) -> int:
    if len(argv) > 1 and argv[1] == "--selfcheck":
        selfcheck()
        return 0
    print(__doc__)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
