apiVersion: v1
kind: Pod
metadata:
  labels:
    policy-as-versioned.dev/policy-version: 4.0.0
  name: corpus
spec:
  containers:
  - image: nginx:1.25
    name: app
    securityContext:
      readOnlyRootFilesystem: false
