apiVersion: v1
kind: Pod
metadata:
  labels:
    policy-as-versioned.dev/policy-version: 5.0.0
    posture.acme.io/caged: true~violated
    posture.acme.io/tier: restricted
  name: corpus
spec:
  containers:
  - image: nginx:1.25
    name: app
